"""add

Revision ID: 71b6c4f0addb
Revises: 4046b9b691ca
Create Date: 2025-12-26 15:53:47.561134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71b6c4f0addb"
down_revision: Union[str, Sequence[str], None] = "4046b9b691ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 1️⃣ объявляем ENUM


def upgrade() -> None:
    # 2️⃣ создаём тип
    order_status = sa.Enum(
        "DRAFT", "PAID", "CANCELED", name="order_status", create_type=True
    )
    order_status.create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 3️⃣ добавляем колонку
    op.add_column(
        "orders",
        sa.Column(
            "status",
            type_=sa.String(),
            existing_type=sa.Enum("DRAFT", "PAID", "CANCELED", name="order_status"),
            existing_nullable=False,
            server_default=None,
        ),
    )
    op.drop_constraint(op.f("uq_orders_user_id"), "orders", type_="unique")
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.create_unique_constraint(
        op.f("uq_orders_user_id"),
        "orders",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("orders", "status")
    # ### end Alembic commands ###
