"""fix

Revision ID: 4046b9b691ca
Revises: 17803302eb44
Create Date: 2025-12-25 11:12:59.381085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4046b9b691ca"
down_revision: Union[str, Sequence[str], None] = "17803302eb44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=postgresql.BYTEA(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        existing_type=sa.String(),
        type_=postgresql.BYTEA(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
