"""create city table

Revision ID: 00a4006e3e82
Revises: 71b6c4f0addb
Create Date: 2025-12-30 08:16:58.974445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00a4006e3e82"
down_revision: Union[str, Sequence[str], None] = "71b6c4f0addb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("city_type", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.Column("district", sa.String(length=255), nullable=True),
        sa.Column("community", sa.String(length=255), nullable=True),
        sa.Column("name_en", sa.String(length=255), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cities")),
    )
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     nullable=False,
    # )
    op.add_column("profiles", sa.Column("city_id", sa.String(length=20), nullable=True))
    op.create_foreign_key(
        op.f("fk_profiles_city_id_cities"),
        "profiles",
        "cities",
        ["city_id"],
        ["id"],
    )
    op.drop_column("profiles", "address")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "address",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("fk_profiles_city_id_cities"), "profiles", type_="foreignkey"
    )
    op.drop_column("profiles", "city_id")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     type_=sa.VARCHAR(),
    #     nullable=True,
    # )
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
