"""add pg_trgm and city search indexes

Revision ID: 2fb8c8ae959f
Revises: 00a4006e3e82
Create Date: 2025-12-30 12:25:11.185203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fb8c8ae959f"
down_revision: Union[str, Sequence[str], None] = "00a4006e3e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     nullable=False,
    # )
    # 1️⃣ pg_trgm extension
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # 2️⃣ Trigram indexes
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_cities_name_trgm
        ON cities USING gin (name gin_trgm_ops)
    """
    )

    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_cities_name_en_trgm
        ON cities USING gin (name_en gin_trgm_ops)
    """
    )

    # 3️⃣ Regular btree indexes
    op.create_index(
        "idx_cities_region",
        "cities",
        ["region"],
        unique=False,
    )

    op.create_index(
        "idx_cities_district",
        "cities",
        ["district"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_cities_name_trgm", table_name="cities")
    op.drop_index("idx_cities_name_en_trgm", table_name="cities")

    op.drop_index("idx_cities_region", table_name="cities")
    op.drop_index("idx_cities_district", table_name="cities")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.Enum(
    #         "draft", "paid", "canceled", name="order_status"
    #     ),
    #     type_=sa.VARCHAR(),
    #     nullable=True,
    # )
    # ### end Alembic commands ###
