"""create refresh_token table

Revision ID: 422108c77dc8
Revises: 2fb8c8ae959f
Create Date: 2026-01-04 10:54:08.668726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "422108c77dc8"
down_revision: Union[str, Sequence[str], None] = "2fb8c8ae959f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token"),
        "refresh_tokens",
        ["token"],
        unique=True,
    )
    # op.drop_index(op.f("idx_cities_district"), table_name="cities")
    # op.drop_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(
    #     op.f("idx_cities_name_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(op.f("idx_cities_region"), table_name="cities")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     nullable=False,
    # )
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.String(),
            nullable=False,
            server_default="user",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("users", "created_at")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "role")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.Enum(
    #         "draft", "paid", "canceled", name="order_status"
    #     ),
    #     type_=sa.VARCHAR(),
    #     nullable=True,
    # )
    # op.create_index(
    #     op.f("idx_cities_region"), "cities", ["region"], unique=False
    # )
    # op.create_index(
    #     op.f("idx_cities_name_trgm"),
    #     "cities",
    #     ["name"],
    #     unique=False,
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     "cities",
    #     ["name_en"],
    #     unique=False,
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_district"), "cities", ["district"], unique=False
    # )
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
