"""create oauth table

Revision ID: f77b84bd1a4a
Revises: 6249032010a4
Create Date: 2026-01-10 16:34:48.047022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f77b84bd1a4a"
down_revision: Union[str, Sequence[str], None] = "6249032010a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_account_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_accounts")),
        sa.UniqueConstraint(
            "provider",
            "provider_account_id",
            name=op.f("uq_oauth_accounts_provider_provider_account_id"),
        ),
    )
    # op.drop_index(op.f("idx_cities_district"), table_name="cities")
    # op.drop_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(
    #     op.f("idx_cities_name_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(op.f("idx_cities_region"), table_name="cities")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     nullable=False,
    # )
    op.alter_column(
        "users",
        "password_hash",
        existing_type=postgresql.BYTEA(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password_hash",
        existing_type=postgresql.BYTEA(),
        nullable=False,
    )
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.Enum(
    #         "draft", "paid", "canceled", name="order_status"
    #     ),
    #     type_=sa.VARCHAR(),
    #     nullable=True,
    # )
    # op.create_index(
    #     op.f("idx_cities_region"), "cities", ["region"], unique=False
    # )
    # op.create_index(
    #     op.f("idx_cities_name_trgm"),
    #     "cities",
    #     ["name"],
    #     unique=False,
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     "cities",
    #     ["name_en"],
    #     unique=False,
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_district"), "cities", ["district"], unique=False
    # )
    op.drop_table("oauth_accounts")
    # ### end Alembic commands ###
