"""fix password in user table

Revision ID: a6b9ce5b7de9
Revises: cdbb12b685b6
Create Date: 2026-01-09 08:00:47.231228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6b9ce5b7de9"
down_revision: Union[str, Sequence[str], None] = "cdbb12b685b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("idx_cities_district"), table_name="cities")
    # op.drop_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(
    #     op.f("idx_cities_name_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(op.f("idx_cities_region"), table_name="cities")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     nullable=False,
    # )
    op.drop_column("users", "password")
    op.add_column(
        "users",
        sa.Column("password", sa.LargeBinary(), nullable=False),
    )
    # op.alter_column(
    #     "users",
    #     "password",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.LargeBinary(),
    #     existing_nullable=False,
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(length=128), nullable=False),
    )
    # op.alter_column(
    #     "users",
    #     "password",
    #     existing_type=sa.LargeBinary(),
    #     type_=sa.VARCHAR(),
    #     existing_nullable=False,
    # )
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     type_=sa.VARCHAR(),
    #     nullable=True,
    # )
    # op.create_index(op.f("idx_cities_region"), "cities", ["region"], unique=False)
    # op.create_index(
    #     op.f("idx_cities_name_trgm"),
    #     "cities",
    #     ["name"],
    #     unique=False,
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     "cities",
    #     ["name_en"],
    #     unique=False,
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(op.f("idx_cities_district"), "cities", ["district"], unique=False)
    # ### end Alembic commands ###
