"""add created_at in refresh_token table

Revision ID: 6249032010a4
Revises: a6b9ce5b7de9
Create Date: 2026-01-09 10:53:46.488235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6249032010a4"
down_revision: Union[str, Sequence[str], None] = "a6b9ce5b7de9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("idx_cities_district"), table_name="cities")
    # op.drop_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(
    #     op.f("idx_cities_name_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(op.f("idx_cities_region"), table_name="cities")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     nullable=False,
    # )
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("users", sa.Column("password_hash", sa.LargeBinary(), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", postgresql.BYTEA(), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "password_hash")
    op.drop_column("refresh_tokens", "created_at")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.Enum(
    #         "draft", "paid", "canceled", name="order_status"
    #     ),
    #     type_=sa.VARCHAR(),
    #     nullable=True,
    # )
    # op.create_index(
    #     op.f("idx_cities_region"), "cities", ["region"], unique=False
    # )
    # op.create_index(
    #     op.f("idx_cities_name_trgm"),
    #     "cities",
    #     ["name"],
    #     unique=False,
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     "cities",
    #     ["name_en"],
    #     unique=False,
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_district"), "cities", ["district"], unique=False
    # )
    # ### end Alembic commands ###
