"""fix created_at in user table

Revision ID: cdbb12b685b6
Revises: 422108c77dc8
Create Date: 2026-01-05 16:38:34.713519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdbb12b685b6"
down_revision: Union[str, Sequence[str], None] = "422108c77dc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("idx_cities_district"), table_name="cities")
    # op.drop_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(
    #     op.f("idx_cities_name_trgm"),
    #     table_name="cities",
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.drop_index(op.f("idx_cities_region"), table_name="cities")
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Enum("draft", "paid", "canceled", name="order_status"),
    #     nullable=False,
    # )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # op.alter_column(
    #     "orders",
    #     "status",
    #     existing_type=sa.Enum(
    #         "draft", "paid", "canceled", name="order_status"
    #     ),
    #     type_=sa.VARCHAR(),
    #     nullable=True,
    # )
    # op.create_index(
    #     op.f("idx_cities_region"), "cities", ["region"], unique=False
    # )
    # op.create_index(
    #     op.f("idx_cities_name_trgm"),
    #     "cities",
    #     ["name"],
    #     unique=False,
    #     postgresql_ops={"name": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_name_en_trgm"),
    #     "cities",
    #     ["name_en"],
    #     unique=False,
    #     postgresql_ops={"name_en": "gin_trgm_ops"},
    #     postgresql_using="gin",
    # )
    # op.create_index(
    #     op.f("idx_cities_district"), "cities", ["district"], unique=False
    # )
    # ### end Alembic commands ###
